#!/bin/bash

if [[ $(pgrep -f "volume_osd" | wc -l) -gt 2 ]]; then
  kill $(pgrep -f "volume_osd" | awk 'NR==1{print $1}')
  eww close volume_osd
  #pgrep -f "volume_osd" | wc -l
fi

if [[ $(pgrep -f "brightness_osd" | wc -l) -gt 2 ]]; then
  kill $(pgrep -f "brightness_osd" | awk 'NR==1{print $1}')
  #pgrep -f "brightness_osd" | wc -l
else
  eww open brightness_osd
fi

sleep 3
eww close brightness_osd
