#!/usr/bin/python

import os

curr_dir = os.getcwd()
curr_dir_items = os.listdir(os.getcwd())
dir_vid_files = list()
vids_mkv = list()
vids_mp4 = list()
prefix = ""

def scan_append(arr):
    global prefix
    for item in arr:
        if os.path.isfile(item):
            extension_tup = os.path.splitext(item)
            if extension_tup[-1] == ".mkv":
                vids_mkv.append({f"{prefix}/{extension_tup[0]}":f"{extension_tup[-1]}"})
            elif extension_tup[-1] == ".mp4":
                vids_mp4.append({f"{prefix}/{extension_tup[0]}":f"{extension_tup[-1]}"})
        elif os.path.isdir(item):
            if os.getcwd() == curr_dir:
                os.chdir(f"{curr_dir}/{item}")
            else:
                os.chdir(f"{curr_dir}/{prefix}/{item}")
            temp_arr = os.listdir()
            if len(prefix) != 0 and os.getcwd() != curr_dir:
                prefix = prefix+"/"+item
            else:
                prefix = item
            scan_append(temp_arr)
            prefix = ""
            os.chdir(curr_dir)

def vid_append(vids_mkv, vids_mp4):
    for i in vids_mkv:
        for key,value in i.items():
            os.system(f"ffmpeg -i \"{key}{value}\" -codec copy \"{key}.mp4\"")
            os.system(f"ffmpeg -i \"{key}.mp4\" -vf scale=960:544 \"{key[:-1]}ep{key[-1]}.mp4\"")
            os.system(f"rm -f {key}{value}")
            os.system(f"rm -f \"{key[:-1]}ep{key[-1]}.mkv\"")
            os.system(f"rm -f \"{key[:-1]}{key[-1]}.mkv\"")
    for i in vids_mp4:
        for key,value in i.items():
            os.system(f"ffmpeg -i {key}{value} -vf scale=960:544 {key[:-1]}ep{key[-1]}.mp4")
            os.system(f"rm -f {key}{value}")
    
scan_append(curr_dir_items)
vid_append(vids_mkv, vids_mp4)
