#!/usr/bin/python

import os,ffmpeg

curr_dir = os.getcwd()
curr_dir_items = os.listdir(os.getcwd())
dir_vid_files = list()
vids = list()
prefix = ""

def scan_append(arr):
    global prefix
    for item in arr:
        if os.path.isfile(item):
            extension_tup = os.path.splitext(item)
            if extension_tup[-1] in [".mp4",".mkv"]:
                vids.append({f"{prefix}{'/' if prefix != '' else ''}{extension_tup[0]}":f"{extension_tup[-1]}"})
        elif os.path.isdir(item):
            if os.getcwd() == curr_dir:
                os.chdir(f"{curr_dir}/{item}")
            else:
                os.chdir(f"{curr_dir}/{prefix}/{item}")
            temp_arr = os.listdir()
            if len(prefix) != 0 and os.getcwd() != curr_dir:
                prefix = prefix+"/"+item
            else:
                prefix = item
            scan_append(temp_arr)
            prefix = ""
            os.chdir(curr_dir)

def convert(arr):
    for i in arr:
        for key,val in i.items():
            stream = ffmpeg.input(f"{key}{val}").video
            audio = ffmpeg.input(f"{key}{val}").audio

            (
                stream
                .filter("scale", "544", "960")
                .output(stream, audio, f"{key}_converted.mp4")
                .run()
            )

scan_append(curr_dir_items)
convert(vids)
