#!/usr/bin/python

import os

curr_dir = os.getcwd()
curr_dir_items = os.listdir(os.getcwd())
dir_vid_files = list()
vids_mkv = list()
vids_mp4 = list()
prefix = ""

def scan_append(arr):
    global prefix
    for item in arr:
        if os.path.isfile(item):
            extension_tup = os.path.splitext(item)
            if extension_tup[-1] == ".mkv":
                vids_mkv.append({f"{prefix}/{extension_tup[0]}":f"{extension_tup[-1]}"})
            elif extension_tup[-1] == ".mp4":
                vids_mp4.append({f"{prefix}/{extension_tup[0]}":f"{extension_tup[-1]}"})
        elif os.path.isdir(item):
            os.chdir(f"{curr_dir}/{item}")
            temp_arr = os.listdir()
            prefix = item
            print(prefix)
            scan_append(temp_arr)
            os.chdir(curr_dir)

def vid_append(vids_mkv, vids_mp4):
    for i in vids_mkv:
        for key,value in i.items():
            print(f"{key[-1]}, {key[:-1]}ep{key[-1]}.mp4")
            os.system(f"ffmpeg -i \"{key}{value}\" -vf scale=960:544 \"{key[:-1]}ep{key[-1]}.mkv\"")
            os.system(f"ffmpeg -i \"{key[:-1]}ep{key[-1]}.mkv\" -codec copy \"{key[:-1]}ep{key[-1]}.mp4\"")
            os.system(f"rm -f {key}{value}")
            os.system(f"rm -f \"{key[:-1]}ep{key[-1]}.mkv\"")
    for i in vids_mp4:
        for key,value in i.items():
            print(f"{key[-1]}, {key[:-1]}ep{key[-1]}.mp4")
            os.system(f"ffmpeg -i {key}{value} -vf scale=960:544 {key[:-1]}ep{key[-1]}.mp4")
            os.system(f"rm -f {key}{value}")
    
scan_append(curr_dir_items)
vid_append(vids_mkv, vids_mp4)
