#!/bin/bash

opt=`eww get power-option`

if [[ $opt == "1" ]]; then
  eww update power-option=1
  hyprlock
elif [[ $opt == "2" ]]; then
  eww update power-option=1
  systemctl suspend
elif [[ $opt == "3" ]]; then
  eww update power-option=1
  pkill Hyprland
elif [[ $opt == "4" ]]; then
  eww update power-option=1
  reboot
elif [[ $opt == "5" ]]; then
  eww update power-option=1
  shutdown -f now
else
  notify-send "Powermenu has encountered a problem!"
  eww update power-option=1
fi
