#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
PS1='[\u@\h \W]\$ '


bind "set completion-ignore-case on"
bind "set show-all-if-ambiguous on"

bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'
bind '"\C-H": shell-backward-kill-word'
bind '"\e[3;5~": shell-kill-word'

export HISTCONTROL=ignoreboth:erasedups
export TERMINAL=foot
export EDITOR=zeditor
