import gi

gi.require_version("Astal", "4.0")
gi.require_version("AstalIO", "0.1")
gi.require_version("Gtk", "4.0")
gi.require_version("Gdk", "4.0")
gi.require_version("Gsk", "4.0")
gi.require_version("GLib", "2.0")
gi.require_version("Gio", "2.0")
gi.require_version("GObject", "2.0")
gi.require_version('Gtk4LayerShell', '1.0')

gi.require_version("AstalBattery", "0.1")
gi.require_version("AstalWp", "0.1")
gi.require_version("AstalNetwork", "0.1")
gi.require_version("AstalTray", "0.1")
gi.require_version("AstalMpris", "0.1")
gi.require_version("AstalHyprland", "0.1")
gi.require_version("AstalNotifd", "0.1")
gi.require_version("AstalApps", "0.1")
