#!/bin/bash

dc="fully-charged"
nc="not charging"
batno="discharging"
batyes="charging"

icon() {
  state=`upower -d | grep "state" | awk -F":" 'NR==1{ print $2 }' | xargs`
  batlvl=`upower -d | grep "percentage" | awk -F":" 'NR==1{ print $2 }' | awk -F"%" '{ print $1 }' | xargs`
  if [ "$state" == "$nc" ]; then
    echo "images/battery-charging.svg"
  elif [ "$state" == "$dc" ]; then
    echo "images/battery-charging.svg"
  elif [ "$state" == "$batyes" ]; then
    echo "images/battery-charging.svg"
  elif [ "$state" == "$batno" ]; then
    if [[ $batlvl -lt 20 ]]; then
      echo "images/battery-20.svg"
    elif [[ $batlvl -lt 40 ]]; then
      echo "images/battery-40.svg"
    elif [[ $batlvl -lt 60 ]]; then
      echo "images/battery-60.svg"
    elif [[ $batlvl -lt 80 ]]; then
      echo "images/battery-80.svg"
    elif [[ $batlvl -le 100 ]]; then
      echo "images/battery-100.svg"
    fi
  fi
}

level() {
  echo -e `upower -d | grep "percentage" | awk -F":" 'NR==1{ print $2 }' | xargs`
}

class() {
  state=`upower -d | grep "state" | awk -F":" 'NR==1{ print $2 }' | xargs`
  batlvl=`upower -d | grep "percentage" | awk -F":" 'NR==1{ print $2 }' | awk -F"%" '{ print $1 }' | xargs`
  if [ "$state" == "$nc" ]; then
    echo "bat-full"
  elif [ "$state" == "$dc" ]; then
    echo "bat-full"
  elif [ "$state" == "$batyes" ]; then
    echo "bat-charging"
  elif [ "$state" == "$batno" ]; then
    if [[ $batlvl -lt 20 ]]; then
      echo "bat-low"
    elif [[ $batlvl -lt 40 ]]; then
      echo "bat-discharging"
    elif [[ $batlvl -lt 60 ]]; then
      echo "bat-discharging"
    elif [[ $batlvl -lt 80 ]]; then
      echo "bat-discharging"
    elif [[ $batlvl -le 100 ]]; then
      echo "bat-discharging"
    fi
  else
    echo "󰑓"
  fi
}

number(){
  echo -e `upower -d | grep "percentage" | awk -F":" 'NR==1{ print $2 }' | awk -F"%" '{ print $1 }' | xargs`
}

if [[ $1 == icon ]]; then
  icon
elif [[ $1 == level ]]; then
  level
elif [[ $1 == class ]]; then
  class
elif [[ $1 == number ]]; then
  number
fi
