#!/bin/sh

calstate=`eww -c ~/.config/eww/bar get cal-rev`

if [[ $calstate == true ]]; then
  eww -c ~/.config/eww/calendar update cal-anim=false ; sleep 0.25 ; eww -c ~/.config/eww/calendar close calendar ; eww -c ~/.config/eww/bar update cal-rev=false
else
  eww -c ~/.config/eww/calendar open calendar ; eww -c ~/.config/eww/bar update cal-rev=true ; sleep 0.01 ; eww -c ~/.config/eww/calendar update cal-anim=true
fi
