#!/bin/bash

calstate=`eww get control-rev`

if [[ $calstate == true ]]; then
  eww -c ./control-center close control-center && eww update control-rev=false
else
  eww -c ./control-center reload && eww -c ./control-center open control-center && eww update control-rev=true
fi
