#!/bin/sh

ccstate=`eww -c ~/.config/eww/bar2 get control-rev`

if [[ $ccstate == "true" ]]; then
  eww -c ~/.config/eww/control update control-anim=false ;
  sleep 0.25 ;
  eww -c ~/.config/eww/control close control-center ;
  eww -c ~/.config/eww/bar2 update control-rev=false ;
else
  eww -c ~/.config/eww/control open control-center ;
  eww -c ~/.config/eww/bar2 update control-rev=true ;
  sleep 0.01 ;
  eww -c ~/.config/eww/control update control-anim=true ;
fi
