#!/bin/bash

workspaces() {
  a=`hyprctl monitors | grep active | awk '{ print $3 }'`
  o=`hyprctl workspaces | grep workspace | awk '{ print $3 }'`
  
  w1=ws
  w2=ws
  w3=ws
  w4=ws
  w5=ws
  w6=ws
  w7=ws
  w8=ws
  w9=ws
  w10=ws

  for i in $o
  do
    eval "w$i=occupied-ws";
  done

  if [[ $a -eq 1 ]]; then
    w1=active-ws
  elif [[ $a -eq 2 ]]; then
    w2=active-ws
  elif [[ $a -eq 3 ]]; then
    w3=active-ws
  elif [[ $a -eq 4 ]]; then
    w4=active-ws
  elif [[ $a -eq 5 ]]; then
    w5=active-ws
  elif [[ $a -eq 6 ]]; then
    w6=active-ws
  elif [[ $a -eq 7 ]]; then
    w7=active-ws
  elif [[ $a -eq 8 ]]; then
    w8=active-ws
  elif [[ $a -eq 9 ]]; then
    w9=active-ws
  elif [[ $a -eq 10 ]]; then
    w10=active-ws
  fi
 
  l1="(box :class \"$w1\")"
  l2="(box :class \"$w2\")"
  l3="(box :class \"$w3\")"
  l4="(box :class \"$w4\")"
  l5="(box :class \"$w5\")"
  l6="(box :class \"$w6\")"
  l7="(box :class \"$w7\")"
  l8="(box :class \"$w8\")"
  l9="(box :class \"$w9\")"
  l10="(box :class \"$w10\")"
  
  echo "(box :space-evenly false :spacing 0 :vexpand true :hexpand false $l1 $l2 $l3 $l4 $l5 $l6)"
 
}

workspaces
socat -U - UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r _ ; do
  workspaces
done
