#!/bin/bash

state(){
  status=`playerctl status`
  meta=`playerctl metadata title`

  if [[ $status == "Playing" ]]; then
    declare -i chars=0
    for ((i=0;i<${#meta};i++)); do
      chars+=1
    done
    if [[ $chars > 20 ]]; then
      echo "Playing: ${meta::20}..."
    else
      echo "Playing: $meta"
    fi
  elif [[ $status == "Paused" ]]; then
    declare -i chars=0
    for ((i=0;i<${#meta};i++)); do
      chars+=1
    done
    if [[ $chars > 20 ]]; then
      echo "${meta::20}... (Paused)"
    else
      echo "$meta (Paused)"
    fi
  else
    echo "Not Playing Anything"
  fi
}

if [[ $1 == "state" ]]; then
  while read -r line; do
    state
  done < <(playerctl --follow status || playerctl --follow metadata)
elif [[ $1 == "art" ]]; then
  while read -r line; do
    art=`playerctl metadata | grep artUrl | awk -F'file://' '{ print $2 }' | xargs`
    if [[ $art == "" ]]; then
      echo "../images/random-colours.png"
    else
      echo $art
    fi
  done < <(playerctl --follow status || playerctl --follow metadata)
fi
