#!/bin/bash

imgdir="images/gruvbox-dark"

strength=`iwconfig wlan0 | grep "Link Quality=" | awk -F'=' '{ print $2 }' | awk -F'/' '{ print $1 }'`
state=`iwconfig wlan0 | grep ESSID | awk -F':' '{ print $2 }' | xargs`
wf=`echo "$strength*100/70" | bc`

icon() {
  if [[ $wf -eq 0 ]]; then
    echo "../$imgdir/wifi-off.svg"
  elif [[ $wf -le 30 ]]; then
#   echo "../$imgdir/wifi-none.svg"
    echo "../$imgdir/wifi-low"
  elif [[ $wf -le 60 ]]; then
#   echo "../$imgdir/wifi-low.svg"
    echo "../$imgdir/wifi-medium.svg"
  elif [[ $wf -gt 60 ]]; then
#   echo "../$imgdir/wifi-medium.svg"
    echo "../$imgdir/wifi-high.svg"
# elif [[ $wf -gt 75 ]]; then
#   echo "../$imgdir/wifi-high.svg"
  else
    echo "../$imgdir/wifi-off.svg"
  fi
}

percentage() {
  echo "$wf%"
}

if [[ $1 == icon ]]; then
  icon
elif [[ $1 == percentage ]]; then
  percentage
elif [[ $1 == name ]]; then
  if [[ $state == "off/any" ]]; then
    echo "Disconnected"
  else
    iwconfig wlan0 | grep ESSID | awk -F'"' '{ print $2 }' | xargs
  fi
fi
