#!/bin/bash

strength=`iwconfig wlan0 | grep "Link Quality=" | awk -F'=' '{ print $2 }' | awk -F'/' '{ print $1 }'`
state=`iwconfig wlan0 | grep ESSID | awk -F':' '{ print $2 }' | xargs`
wf=`echo "$strength*100/70" | bc`

icon() {
  if [[ $strength -eq 0 ]]; then
    echo "./images/wifi-off.svg"
  elif [[ $strength -le 25 ]]; then
    echo "./images/wifi-none.svg"
  elif [[ $strength -le 50 ]]; then 
    echo "./images/wifi-low.svg"
  elif [[ $strength -le 75 ]]; then
    echo "./images/wifi-medium.svg"
  elif [[ $strength -gt 75 ]]; then
    echo "./images/wifi-high.svg"
  else
    echo "./images/wifi-off.svg"
  fi
}

percentage() {
  echo "$wf%"
}

if [[ $1 == icon ]]; then
  icon
elif [[ $1 == percentage ]]; then
  percentage
elif [[ $1 == name ]]; then
  if [[ $state == "off/any" ]]; then
    echo "Disconnected"
  else
    iwconfig wlan0 | grep ESSID | awk -F'"' '{ print $2 }' | xargs
  fi
fi
