#!/bin/bash

workspaces() {
  a=`hyprctl monitors | awk 'FNR == 7 { print $3 }'`
  o=`hyprctl workspaces | awk '{ print $4 }' | egrep -o '[0-9]+'`
  
  w1=bar-ws
  w2=bar-ws
  w3=bar-ws
  w4=bar-ws
  w5=bar-ws
  w6=bar-ws
  w7=bar-ws
  w8=bar-ws
  w9=bar-ws
  w10=bar-ws

  icon1=./images/diamond.svg
  icon2=./images/diamond.svg
  icon3=./images/diamond.svg
  icon4=./images/diamond.svg
  icon5=./images/diamond.svg
  icon6=./images/diamond.svg
  icon7=./images/diamond.svg
  icon8=./images/diamond.svg
  icon9=./images/diamond.svg
  icon10=./images/diamond.svg

  for i in $o
  do
    eval "w$i=bar-occupied-ws";
    eval "icon$i=./images/diamond-occupied.svg"
  done

  if [[ $a -eq 1 ]]; then
    w1=bar-active-ws
    icon1=./images/diamond-active.svg
  elif [[ $a -eq 2 ]]; then
    w2=bar-active-ws
    icon2=./images/diamond-active.svg
  elif [[ $a -eq 3 ]]; then
    w3=bar-active-ws
    icon3=./images/diamond-active.svg
  elif [[ $a -eq 4 ]]; then
    w4=bar-active-ws
    icon4=./images/diamond-active.svg
  elif [[ $a -eq 5 ]]; then
    w5=bar-active-ws
    icon5=./images/diamond-active.svg
  elif [[ $a -eq 6 ]]; then
    w6=bar-active-ws
    icon6=./images/diamond-active.svg
  elif [[ $a -eq 7 ]]; then
    w7=bar-active-ws
    icon7=./images/diamond-active.svg
  elif [[ $a -eq 8 ]]; then
    w8=bar-active-ws
    icon8=./images/diamond-active.svg
  elif [[ $a -eq 9 ]]; then
    w9=bar-active-ws
    icon9=./images/diamond-active.svg
  elif [[ $a -eq 10 ]]; then
    w10=bar-active-ws
    icon10=./images/diamond-active.svg
  fi
 

  l1="(image :class \"$w1\" :path \"$icon1\" :image-width \"24\" :image-height \"24\")"
  l2="(image :class \"$w2\" :path \"$icon2\" :image-width \"24\" :image-height \"24\")"
  l3="(image :class \"$w3\" :path \"$icon3\" :image-width \"24\" :image-height \"24\")"
  l4="(image :class \"$w4\" :path \"$icon4\" :image-width \"24\" :image-height \"24\")"
  l5="(image :class \"$w5\" :path \"$icon5\" :image-width \"24\" :image-height \"24\")"
  l6="(image :class \"$w6\" :path \"$icon6\" :image-width \"24\" :image-height \"24\")"
  l7="(image :class \"$w7\" :path \"$icon7\" :image-width \"24\" :image-height \"24\")"
  l8="(image :class \"$w8\" :path \"$icon8\" :image-width \"24\" :image-height \"24\")"
  l9="(image :class \"$w9\" :path \"$icon9\" :image-width \"24\" :image-height \"24\")"
  l10="(image :class \"$w10\" :path \"$icon10\" :image-width \"24\" :image-height \"24\")"


#   if [[ $w1 == 'bar-ws' ]]; then
#     l1=""
#   fi

#   if [[ $w2 == 'bar-ws' ]]; then
#     l2=""
#   fi

#   if [[ $w3 == 'bar-ws' ]]; then
#     l3=""
#   fi

#   if [[ $w4 == 'bar-ws' ]]; then
#     l4=""
#   fi

#   if [[ $w5 == 'bar-ws' ]]; then
#     l5=""
#   fi

#   if [[ $w6 == 'bar-ws' ]]; then
#     l6=""
#   fi

#   if [[ $w7 == 'bar-ws' ]]; then
#     l7=""
#   fi

#   if [[ $w8 == 'bar-ws' ]]; then
#     l8=""
#   fi

#   if [[ $w9 == 'bar-ws' ]]; then
#     l9=""
#   fi

#   if [[ $w10 == 'bar-ws' ]]; then
#     l10=""
#   fi

   echo "(box :class \"bar-workspace\" :orientation \"h\" :spacing 0 :space-evenly false :halign \"start\" :hexpand false $l1 $l2 $l3 $l4 $l5 $l6 $l7 $l8 $l9 $l10 )"
 

#  echo "(box :class \"bar-workspace\" :orientation \"v\" :valign \"start\" (label :class \"$w1\" :text \"一\") (label :class \"$w2\" :text \"二\") (label :class \"$w3\" :text \"三\") (label :class \"$w4\" :text \"四\") (label :class \"$w5\" :text \"五\") (label :class \"$w6\" :text \"六\") (label :class \"$w7\" :text \"七\") (label :class \"$w8\" :text \"八\") (label :class \"$w9\" :text \"九\") (label :class \"$w10\" :text \"十\"))"
}

workspaces
socat -U - UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r _ ; do
  workspaces
done
