#!/bin/bash

export eww='~/.eww/target/release/eww'
export DESKTOP_SESSION="bspwm"
xsetroot -cursor_name left_ptr
sxhkd &
 
bspc config border_width	2
bspc config window_gap		4
 
bspc config split_ratio		0.5
bspc config focus_follows_pointer	false
bspc config pointer_modifier	mod4
 
bspc config automatic_scheme	alternate

bspc monitor -d 1 2 3 4 5

# Autostart
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dunst &
feh --bg-fill ~/.config/bspwm/wallpaper.jpg
picom &
$eww daemon ; $eww -c ~/.config/eww/bar open bar
~/.config/bspwm/fullscreen.sh &

